In [1]:
import pandas as pd

In [2]:
pd.__version__

'0.23.4'

In [68]:
# Reading exam data
exam_data = pd.read_csv('./data/exams.csv')
exam_data

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>gender</th>
      <th>race/ethnicity</th>
      <th>parental level of education</th>
      <th>lunch</th>
      <th>test preparation course</th>
      <th>math score</th>
      <th>reading score</th>
      <th>writing score</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>male</td>
      <td>group E</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>79</td>
      <td>75</td>
      <td>81</td>
    </tr>
    <tr>
      <th>1</th>
      <td>female</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>56</td>
      <td>65</td>
      <td>64</td>
    </tr>
    <tr>
      <th>2</th>
      <td>male</td>
      <td>group D</td>
      <td>bachelor's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>86</td>
      <td>68</td>
      <td>74</td>
    </tr>
    <tr>
      <th>3</th>
      <td>female</td>
      <td>group A</td>
      <td>bachelor's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>68</td>
      <td>78</td>
      <td>76</td>
    </tr>
    <tr>
      <th>4</th>
      <td>female</td>
      <td>group D</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>49</td>
      <td>68</td>
      <td>61</td>
    </tr>
    <tr>
      <th>5</th>
      <td>male</td>
      <td>group D</td>
      <td>some high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>49</td>
      <td>47</td>
      <td>41</td>
    </tr>
    <tr>
      <th>6</th>
      <td>male</td>
      <td>group C</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>87</td>
      <td>78</td>
      <td>70</td>
    </tr>
    <tr>
      <th>7</th>
      <td>male</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>74</td>
      <td>80</td>
      <td>76</td>
    </tr>
    <tr>
      <th>8</th>
      <td>female</td>
      <td>group B</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>50</td>
      <td>44</td>
      <td>48</td>
    </tr>
    <tr>
      <th>9</th>
      <td>male</td>
      <td>group A</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>40</td>
      <td>23</td>
      <td>23</td>
    </tr>
    <tr>
      <th>10</th>
      <td>female</td>
      <td>group D</td>
      <td>some high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>68</td>
      <td>75</td>
      <td>77</td>
    </tr>
    <tr>
      <th>11</th>
      <td>female</td>
      <td>group B</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>82</td>
      <td>87</td>
      <td>87</td>
    </tr>
    <tr>
      <th>12</th>
      <td>male</td>
      <td>group A</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>83</td>
      <td>79</td>
      <td>76</td>
    </tr>
    <tr>
      <th>13</th>
      <td>female</td>
      <td>group B</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>56</td>
      <td>66</td>
      <td>74</td>
    </tr>
    <tr>
      <th>14</th>
      <td>male</td>
      <td>group C</td>
      <td>high school</td>
      <td>standard</td>
      <td>none</td>
      <td>62</td>
      <td>56</td>
      <td>53</td>
    </tr>
    <tr>
      <th>15</th>
      <td>female</td>
      <td>group B</td>
      <td>master's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>57</td>
      <td>68</td>
      <td>71</td>
    </tr>
    <tr>
      <th>16</th>
      <td>male</td>
      <td>group B</td>
      <td>high school</td>
      <td>standard</td>
      <td>none</td>
      <td>77</td>
      <td>59</td>
      <td>54</td>
    </tr>
    <tr>
      <th>17</th>
      <td>female</td>
      <td>group C</td>
      <td>some college</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>49</td>
      <td>62</td>
      <td>56</td>
    </tr>
    <tr>
      <th>18</th>
      <td>female</td>
      <td>group B</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>59</td>
      <td>67</td>
      <td>71</td>
    </tr>
    <tr>
      <th>19</th>
      <td>male</td>
      <td>group A</td>
      <td>some college</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>63</td>
      <td>52</td>
      <td>52</td>
    </tr>
    <tr>
      <th>20</th>
      <td>male</td>
      <td>group B</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>64</td>
      <td>61</td>
      <td>61</td>
    </tr>
    <tr>
      <th>21</th>
      <td>female</td>
      <td>group C</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>54</td>
      <td>64</td>
      <td>59</td>
    </tr>
    <tr>
      <th>22</th>
      <td>male</td>
      <td>group C</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>88</td>
      <td>81</td>
      <td>83</td>
    </tr>
    <tr>
      <th>23</th>
      <td>male</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>62</td>
      <td>55</td>
      <td>52</td>
    </tr>
    <tr>
      <th>24</th>
      <td>male</td>
      <td>group D</td>
      <td>bachelor's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>52</td>
      <td>66</td>
      <td>56</td>
    </tr>
    <tr>
      <th>25</th>
      <td>male</td>
      <td>group B</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>91</td>
      <td>86</td>
      <td>82</td>
    </tr>
    <tr>
      <th>26</th>
      <td>female</td>
      <td>group C</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>33</td>
      <td>42</td>
      <td>41</td>
    </tr>
    <tr>
      <th>27</th>
      <td>female</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>66</td>
      <td>76</td>
      <td>73</td>
    </tr>
    <tr>
      <th>28</th>
      <td>female</td>
      <td>group B</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>33</td>
      <td>47</td>
      <td>39</td>
    </tr>
    <tr>
      <th>29</th>
      <td>male</td>
      <td>group E</td>
      <td>some college</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>74</td>
      <td>73</td>
      <td>76</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>70</th>
      <td>female</td>
      <td>group E</td>
      <td>bachelor's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>68</td>
      <td>80</td>
      <td>79</td>
    </tr>
    <tr>
      <th>71</th>
      <td>male</td>
      <td>group C</td>
      <td>some high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>53</td>
      <td>51</td>
      <td>46</td>
    </tr>
    <tr>
      <th>72</th>
      <td>female</td>
      <td>group C</td>
      <td>some high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>56</td>
      <td>56</td>
      <td>54</td>
    </tr>
    <tr>
      <th>73</th>
      <td>male</td>
      <td>group C</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>63</td>
      <td>61</td>
      <td>55</td>
    </tr>
    <tr>
      <th>74</th>
      <td>male</td>
      <td>group D</td>
      <td>some high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>60</td>
      <td>63</td>
      <td>57</td>
    </tr>
    <tr>
      <th>75</th>
      <td>male</td>
      <td>group D</td>
      <td>master's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>70</td>
      <td>69</td>
      <td>73</td>
    </tr>
    <tr>
      <th>76</th>
      <td>male</td>
      <td>group B</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>64</td>
      <td>64</td>
      <td>60</td>
    </tr>
    <tr>
      <th>77</th>
      <td>female</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>52</td>
      <td>73</td>
      <td>68</td>
    </tr>
    <tr>
      <th>78</th>
      <td>female</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>61</td>
      <td>76</td>
      <td>79</td>
    </tr>
    <tr>
      <th>79</th>
      <td>female</td>
      <td>group B</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>63</td>
      <td>70</td>
      <td>78</td>
    </tr>
    <tr>
      <th>80</th>
      <td>male</td>
      <td>group D</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>74</td>
      <td>72</td>
      <td>74</td>
    </tr>
    <tr>
      <th>81</th>
      <td>male</td>
      <td>group C</td>
      <td>bachelor's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>83</td>
      <td>83</td>
      <td>86</td>
    </tr>
    <tr>
      <th>82</th>
      <td>male</td>
      <td>group C</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>67</td>
      <td>61</td>
      <td>56</td>
    </tr>
    <tr>
      <th>83</th>
      <td>male</td>
      <td>group B</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>47</td>
      <td>58</td>
      <td>53</td>
    </tr>
    <tr>
      <th>84</th>
      <td>female</td>
      <td>group C</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>62</td>
      <td>63</td>
      <td>72</td>
    </tr>
    <tr>
      <th>85</th>
      <td>male</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>58</td>
      <td>56</td>
      <td>64</td>
    </tr>
    <tr>
      <th>86</th>
      <td>female</td>
      <td>group B</td>
      <td>some college</td>
      <td>standard</td>
      <td>completed</td>
      <td>60</td>
      <td>75</td>
      <td>74</td>
    </tr>
    <tr>
      <th>87</th>
      <td>male</td>
      <td>group B</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>64</td>
      <td>58</td>
      <td>64</td>
    </tr>
    <tr>
      <th>88</th>
      <td>female</td>
      <td>group D</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>78</td>
      <td>82</td>
      <td>82</td>
    </tr>
    <tr>
      <th>89</th>
      <td>female</td>
      <td>group C</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>57</td>
      <td>65</td>
      <td>66</td>
    </tr>
    <tr>
      <th>90</th>
      <td>male</td>
      <td>group C</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>97</td>
      <td>91</td>
      <td>96</td>
    </tr>
    <tr>
      <th>91</th>
      <td>male</td>
      <td>group C</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>72</td>
      <td>68</td>
      <td>66</td>
    </tr>
    <tr>
      <th>92</th>
      <td>female</td>
      <td>group D</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>71</td>
      <td>77</td>
      <td>76</td>
    </tr>
    <tr>
      <th>93</th>
      <td>female</td>
      <td>group A</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>44</td>
      <td>57</td>
      <td>62</td>
    </tr>
    <tr>
      <th>94</th>
      <td>female</td>
      <td>group B</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>69</td>
      <td>89</td>
      <td>83</td>
    </tr>
    <tr>
      <th>95</th>
      <td>female</td>
      <td>group A</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>59</td>
      <td>76</td>
      <td>80</td>
    </tr>
    <tr>
      <th>96</th>
      <td>female</td>
      <td>group D</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>60</td>
      <td>62</td>
      <td>61</td>
    </tr>
    <tr>
      <th>97</th>
      <td>female</td>
      <td>group C</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>69</td>
      <td>82</td>
      <td>83</td>
    </tr>
    <tr>
      <th>98</th>
      <td>male</td>
      <td>group D</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>89</td>
      <td>83</td>
      <td>79</td>
    </tr>
    <tr>
      <th>99</th>
      <td>female</td>
      <td>group A</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>65</td>
      <td>88</td>
      <td>88</td>
    </tr>
  </tbody>
</table>
<p>100 rows × 8 columns</p>
</div>

In [69]:
math_average = exam_data['math score'].mean()
reading_average = exam_data['reading score'].mean()
writing_average = exam_data['writing score'].mean()

print("Math avg: ", math_average)
print('Reading avg: ', reading_average)
print("Writing avg: ", writing_average)

Math avg:  65.06
Reading avg:  67.28
Writing avg:  66.47

In [70]:
# sklearn has a module called preprocessing that helps with standardization
from sklearn import preprocessing

exam_data[['math score']] = preprocessing.scale(exam_data[['math score']])
exam_data[['reading score']] = preprocessing.scale(exam_data[['reading score']])
exam_data[['writing score']] = preprocessing.scale(exam_data[['writing score']])

exam_data

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>gender</th>
      <th>race/ethnicity</th>
      <th>parental level of education</th>
      <th>lunch</th>
      <th>test preparation course</th>
      <th>math score</th>
      <th>reading score</th>
      <th>writing score</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>male</td>
      <td>group E</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>0.994557</td>
      <td>0.574138</td>
      <td>1.049901</td>
    </tr>
    <tr>
      <th>1</th>
      <td>female</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.646391</td>
      <td>-0.169564</td>
      <td>-0.178476</td>
    </tr>
    <tr>
      <th>2</th>
      <td>male</td>
      <td>group D</td>
      <td>bachelor's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>1.493976</td>
      <td>0.053547</td>
      <td>0.544099</td>
    </tr>
    <tr>
      <th>3</th>
      <td>female</td>
      <td>group A</td>
      <td>bachelor's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>0.209756</td>
      <td>0.797248</td>
      <td>0.688613</td>
    </tr>
    <tr>
      <th>4</th>
      <td>female</td>
      <td>group D</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-1.145810</td>
      <td>0.053547</td>
      <td>-0.395248</td>
    </tr>
    <tr>
      <th>5</th>
      <td>male</td>
      <td>group D</td>
      <td>some high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-1.145810</td>
      <td>-1.508227</td>
      <td>-1.840397</td>
    </tr>
    <tr>
      <th>6</th>
      <td>male</td>
      <td>group C</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>1.565321</td>
      <td>0.797248</td>
      <td>0.255069</td>
    </tr>
    <tr>
      <th>7</th>
      <td>male</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>0.637829</td>
      <td>0.945989</td>
      <td>0.688613</td>
    </tr>
    <tr>
      <th>8</th>
      <td>female</td>
      <td>group B</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>-1.074464</td>
      <td>-1.731338</td>
      <td>-1.334595</td>
    </tr>
    <tr>
      <th>9</th>
      <td>male</td>
      <td>group A</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>-1.787920</td>
      <td>-3.293112</td>
      <td>-3.141031</td>
    </tr>
    <tr>
      <th>10</th>
      <td>female</td>
      <td>group D</td>
      <td>some high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>0.209756</td>
      <td>0.574138</td>
      <td>0.760871</td>
    </tr>
    <tr>
      <th>11</th>
      <td>female</td>
      <td>group B</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>1.208594</td>
      <td>1.466580</td>
      <td>1.483445</td>
    </tr>
    <tr>
      <th>12</th>
      <td>male</td>
      <td>group A</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>1.279939</td>
      <td>0.871619</td>
      <td>0.688613</td>
    </tr>
    <tr>
      <th>13</th>
      <td>female</td>
      <td>group B</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>-0.646391</td>
      <td>-0.095194</td>
      <td>0.544099</td>
    </tr>
    <tr>
      <th>14</th>
      <td>male</td>
      <td>group C</td>
      <td>high school</td>
      <td>standard</td>
      <td>none</td>
      <td>-0.218317</td>
      <td>-0.838896</td>
      <td>-0.973308</td>
    </tr>
    <tr>
      <th>15</th>
      <td>female</td>
      <td>group B</td>
      <td>master's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>-0.575045</td>
      <td>0.053547</td>
      <td>0.327326</td>
    </tr>
    <tr>
      <th>16</th>
      <td>male</td>
      <td>group B</td>
      <td>high school</td>
      <td>standard</td>
      <td>none</td>
      <td>0.851866</td>
      <td>-0.615785</td>
      <td>-0.901050</td>
    </tr>
    <tr>
      <th>17</th>
      <td>female</td>
      <td>group C</td>
      <td>some college</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-1.145810</td>
      <td>-0.392675</td>
      <td>-0.756535</td>
    </tr>
    <tr>
      <th>18</th>
      <td>female</td>
      <td>group B</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>-0.432354</td>
      <td>-0.020824</td>
      <td>0.327326</td>
    </tr>
    <tr>
      <th>19</th>
      <td>male</td>
      <td>group A</td>
      <td>some college</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.146972</td>
      <td>-1.136376</td>
      <td>-1.045565</td>
    </tr>
    <tr>
      <th>20</th>
      <td>male</td>
      <td>group B</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>-0.075626</td>
      <td>-0.467045</td>
      <td>-0.395248</td>
    </tr>
    <tr>
      <th>21</th>
      <td>female</td>
      <td>group C</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.789082</td>
      <td>-0.243934</td>
      <td>-0.539763</td>
    </tr>
    <tr>
      <th>22</th>
      <td>male</td>
      <td>group C</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>1.636667</td>
      <td>1.020359</td>
      <td>1.194416</td>
    </tr>
    <tr>
      <th>23</th>
      <td>male</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>-0.218317</td>
      <td>-0.913266</td>
      <td>-1.045565</td>
    </tr>
    <tr>
      <th>24</th>
      <td>male</td>
      <td>group D</td>
      <td>bachelor's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.931773</td>
      <td>-0.095194</td>
      <td>-0.756535</td>
    </tr>
    <tr>
      <th>25</th>
      <td>male</td>
      <td>group B</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>1.850704</td>
      <td>1.392210</td>
      <td>1.122158</td>
    </tr>
    <tr>
      <th>26</th>
      <td>female</td>
      <td>group C</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-2.287338</td>
      <td>-1.880078</td>
      <td>-1.840397</td>
    </tr>
    <tr>
      <th>27</th>
      <td>female</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>0.067065</td>
      <td>0.648508</td>
      <td>0.471841</td>
    </tr>
    <tr>
      <th>28</th>
      <td>female</td>
      <td>group B</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>-2.287338</td>
      <td>-1.508227</td>
      <td>-1.984912</td>
    </tr>
    <tr>
      <th>29</th>
      <td>male</td>
      <td>group E</td>
      <td>some college</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>0.637829</td>
      <td>0.425397</td>
      <td>0.688613</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>70</th>
      <td>female</td>
      <td>group E</td>
      <td>bachelor's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>0.209756</td>
      <td>0.945989</td>
      <td>0.905386</td>
    </tr>
    <tr>
      <th>71</th>
      <td>male</td>
      <td>group C</td>
      <td>some high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.860427</td>
      <td>-1.210747</td>
      <td>-1.479110</td>
    </tr>
    <tr>
      <th>72</th>
      <td>female</td>
      <td>group C</td>
      <td>some high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>-0.646391</td>
      <td>-0.838896</td>
      <td>-0.901050</td>
    </tr>
    <tr>
      <th>73</th>
      <td>male</td>
      <td>group C</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-0.146972</td>
      <td>-0.467045</td>
      <td>-0.828793</td>
    </tr>
    <tr>
      <th>74</th>
      <td>male</td>
      <td>group D</td>
      <td>some high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>-0.361008</td>
      <td>-0.318304</td>
      <td>-0.684278</td>
    </tr>
    <tr>
      <th>75</th>
      <td>male</td>
      <td>group D</td>
      <td>master's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>0.352447</td>
      <td>0.127917</td>
      <td>0.471841</td>
    </tr>
    <tr>
      <th>76</th>
      <td>male</td>
      <td>group B</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>-0.075626</td>
      <td>-0.243934</td>
      <td>-0.467506</td>
    </tr>
    <tr>
      <th>77</th>
      <td>female</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-0.931773</td>
      <td>0.425397</td>
      <td>0.110554</td>
    </tr>
    <tr>
      <th>78</th>
      <td>female</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>-0.289663</td>
      <td>0.648508</td>
      <td>0.905386</td>
    </tr>
    <tr>
      <th>79</th>
      <td>female</td>
      <td>group B</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>-0.146972</td>
      <td>0.202287</td>
      <td>0.833128</td>
    </tr>
    <tr>
      <th>80</th>
      <td>male</td>
      <td>group D</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>0.637829</td>
      <td>0.351027</td>
      <td>0.544099</td>
    </tr>
    <tr>
      <th>81</th>
      <td>male</td>
      <td>group C</td>
      <td>bachelor's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>1.279939</td>
      <td>1.169099</td>
      <td>1.411188</td>
    </tr>
    <tr>
      <th>82</th>
      <td>male</td>
      <td>group C</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>0.138410</td>
      <td>-0.467045</td>
      <td>-0.756535</td>
    </tr>
    <tr>
      <th>83</th>
      <td>male</td>
      <td>group B</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-1.288501</td>
      <td>-0.690155</td>
      <td>-0.973308</td>
    </tr>
    <tr>
      <th>84</th>
      <td>female</td>
      <td>group C</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.218317</td>
      <td>-0.318304</td>
      <td>0.399584</td>
    </tr>
    <tr>
      <th>85</th>
      <td>male</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>-0.503700</td>
      <td>-0.838896</td>
      <td>-0.178476</td>
    </tr>
    <tr>
      <th>86</th>
      <td>female</td>
      <td>group B</td>
      <td>some college</td>
      <td>standard</td>
      <td>completed</td>
      <td>-0.361008</td>
      <td>0.574138</td>
      <td>0.544099</td>
    </tr>
    <tr>
      <th>87</th>
      <td>male</td>
      <td>group B</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-0.075626</td>
      <td>-0.690155</td>
      <td>-0.178476</td>
    </tr>
    <tr>
      <th>88</th>
      <td>female</td>
      <td>group D</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>0.923211</td>
      <td>1.094729</td>
      <td>1.122158</td>
    </tr>
    <tr>
      <th>89</th>
      <td>female</td>
      <td>group C</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-0.575045</td>
      <td>-0.169564</td>
      <td>-0.033961</td>
    </tr>
    <tr>
      <th>90</th>
      <td>male</td>
      <td>group C</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>2.278777</td>
      <td>1.764061</td>
      <td>2.133762</td>
    </tr>
    <tr>
      <th>91</th>
      <td>male</td>
      <td>group C</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>0.495138</td>
      <td>0.053547</td>
      <td>-0.033961</td>
    </tr>
    <tr>
      <th>92</th>
      <td>female</td>
      <td>group D</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>0.423793</td>
      <td>0.722878</td>
      <td>0.688613</td>
    </tr>
    <tr>
      <th>93</th>
      <td>female</td>
      <td>group A</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-1.502537</td>
      <td>-0.764526</td>
      <td>-0.322991</td>
    </tr>
    <tr>
      <th>94</th>
      <td>female</td>
      <td>group B</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>0.281101</td>
      <td>1.615320</td>
      <td>1.194416</td>
    </tr>
    <tr>
      <th>95</th>
      <td>female</td>
      <td>group A</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-0.432354</td>
      <td>0.648508</td>
      <td>0.977643</td>
    </tr>
    <tr>
      <th>96</th>
      <td>female</td>
      <td>group D</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.361008</td>
      <td>-0.392675</td>
      <td>-0.395248</td>
    </tr>
    <tr>
      <th>97</th>
      <td>female</td>
      <td>group C</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>0.281101</td>
      <td>1.094729</td>
      <td>1.194416</td>
    </tr>
    <tr>
      <th>98</th>
      <td>male</td>
      <td>group D</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>1.708013</td>
      <td>1.169099</td>
      <td>0.905386</td>
    </tr>
    <tr>
      <th>99</th>
      <td>female</td>
      <td>group A</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-0.004281</td>
      <td>1.540950</td>
      <td>1.555703</td>
    </tr>
  </tbody>
</table>
<p>100 rows × 8 columns</p>
</div>

In [71]:
# Need to convert text values into numbers
# Can use label encoding or one-hot encoding (see other notebook for explanation of these)
le = preprocessing.LabelEncoder()
exam_data['gender'] = le.fit_transform(exam_data['gender'].astype(str))
exam_data.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>gender</th>
      <th>race/ethnicity</th>
      <th>parental level of education</th>
      <th>lunch</th>
      <th>test preparation course</th>
      <th>math score</th>
      <th>reading score</th>
      <th>writing score</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>group E</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>0.994557</td>
      <td>0.574138</td>
      <td>1.049901</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>group C</td>
      <td>associate's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.646391</td>
      <td>-0.169564</td>
      <td>-0.178476</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1</td>
      <td>group D</td>
      <td>bachelor's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>1.493976</td>
      <td>0.053547</td>
      <td>0.544099</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0</td>
      <td>group A</td>
      <td>bachelor's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>0.209756</td>
      <td>0.797248</td>
      <td>0.688613</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>group D</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-1.145810</td>
      <td>0.053547</td>
      <td>-0.395248</td>
    </tr>
  </tbody>
</table>
</div>

In [72]:
# gives unique values of gender that the column holds (it's supposed to give 'male', 'female'. 
# If it doesn't, rerun the cell for reading the data)
le.classes_

array(['female', 'male'], dtype=object)

In [73]:
# One-hot representation
pd.get_dummies(exam_data['race/ethnicity'])

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>group A</th>
      <th>group B</th>
      <th>group C</th>
      <th>group D</th>
      <th>group E</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>9</th>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>10</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>12</th>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>13</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>14</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>15</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>16</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>17</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>18</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19</th>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>20</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>21</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>22</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>23</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>24</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>25</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>26</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>27</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>28</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>29</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>70</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>71</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>72</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>73</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>74</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>75</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>76</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>77</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>78</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>79</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>80</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>81</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>82</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>83</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>84</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>85</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>86</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>87</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>88</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>89</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>90</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>91</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>92</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>93</th>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>94</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>95</th>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>96</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>97</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>98</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>99</th>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
<p>100 rows × 5 columns</p>
</div>

In [74]:
exam_data = pd.get_dummies(exam_data, columns=['race/ethnicity'])
exam_data

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>gender</th>
      <th>parental level of education</th>
      <th>lunch</th>
      <th>test preparation course</th>
      <th>math score</th>
      <th>reading score</th>
      <th>writing score</th>
      <th>race/ethnicity_group A</th>
      <th>race/ethnicity_group B</th>
      <th>race/ethnicity_group C</th>
      <th>race/ethnicity_group D</th>
      <th>race/ethnicity_group E</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>0.994557</td>
      <td>0.574138</td>
      <td>1.049901</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>associate's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.646391</td>
      <td>-0.169564</td>
      <td>-0.178476</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1</td>
      <td>bachelor's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>1.493976</td>
      <td>0.053547</td>
      <td>0.544099</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0</td>
      <td>bachelor's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>0.209756</td>
      <td>0.797248</td>
      <td>0.688613</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-1.145810</td>
      <td>0.053547</td>
      <td>-0.395248</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>5</th>
      <td>1</td>
      <td>some high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-1.145810</td>
      <td>-1.508227</td>
      <td>-1.840397</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>1</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>1.565321</td>
      <td>0.797248</td>
      <td>0.255069</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>1</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>0.637829</td>
      <td>0.945989</td>
      <td>0.688613</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>-1.074464</td>
      <td>-1.731338</td>
      <td>-1.334595</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>9</th>
      <td>1</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>-1.787920</td>
      <td>-3.293112</td>
      <td>-3.141031</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>10</th>
      <td>0</td>
      <td>some high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>0.209756</td>
      <td>0.574138</td>
      <td>0.760871</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>0</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>1.208594</td>
      <td>1.466580</td>
      <td>1.483445</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>12</th>
      <td>1</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>1.279939</td>
      <td>0.871619</td>
      <td>0.688613</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>13</th>
      <td>0</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>-0.646391</td>
      <td>-0.095194</td>
      <td>0.544099</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>14</th>
      <td>1</td>
      <td>high school</td>
      <td>standard</td>
      <td>none</td>
      <td>-0.218317</td>
      <td>-0.838896</td>
      <td>-0.973308</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>15</th>
      <td>0</td>
      <td>master's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>-0.575045</td>
      <td>0.053547</td>
      <td>0.327326</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>16</th>
      <td>1</td>
      <td>high school</td>
      <td>standard</td>
      <td>none</td>
      <td>0.851866</td>
      <td>-0.615785</td>
      <td>-0.901050</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>17</th>
      <td>0</td>
      <td>some college</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-1.145810</td>
      <td>-0.392675</td>
      <td>-0.756535</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>18</th>
      <td>0</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>-0.432354</td>
      <td>-0.020824</td>
      <td>0.327326</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19</th>
      <td>1</td>
      <td>some college</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.146972</td>
      <td>-1.136376</td>
      <td>-1.045565</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>20</th>
      <td>1</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>-0.075626</td>
      <td>-0.467045</td>
      <td>-0.395248</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>21</th>
      <td>0</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.789082</td>
      <td>-0.243934</td>
      <td>-0.539763</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>22</th>
      <td>1</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>1.636667</td>
      <td>1.020359</td>
      <td>1.194416</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>23</th>
      <td>1</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>-0.218317</td>
      <td>-0.913266</td>
      <td>-1.045565</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>24</th>
      <td>1</td>
      <td>bachelor's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.931773</td>
      <td>-0.095194</td>
      <td>-0.756535</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>25</th>
      <td>1</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>1.850704</td>
      <td>1.392210</td>
      <td>1.122158</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>26</th>
      <td>0</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-2.287338</td>
      <td>-1.880078</td>
      <td>-1.840397</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>27</th>
      <td>0</td>
      <td>associate's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>0.067065</td>
      <td>0.648508</td>
      <td>0.471841</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>28</th>
      <td>0</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>-2.287338</td>
      <td>-1.508227</td>
      <td>-1.984912</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>29</th>
      <td>1</td>
      <td>some college</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>0.637829</td>
      <td>0.425397</td>
      <td>0.688613</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>70</th>
      <td>0</td>
      <td>bachelor's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>0.209756</td>
      <td>0.945989</td>
      <td>0.905386</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>71</th>
      <td>1</td>
      <td>some high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.860427</td>
      <td>-1.210747</td>
      <td>-1.479110</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>72</th>
      <td>0</td>
      <td>some high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>-0.646391</td>
      <td>-0.838896</td>
      <td>-0.901050</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>73</th>
      <td>1</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-0.146972</td>
      <td>-0.467045</td>
      <td>-0.828793</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>74</th>
      <td>1</td>
      <td>some high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>-0.361008</td>
      <td>-0.318304</td>
      <td>-0.684278</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>75</th>
      <td>1</td>
      <td>master's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>0.352447</td>
      <td>0.127917</td>
      <td>0.471841</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>76</th>
      <td>1</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>-0.075626</td>
      <td>-0.243934</td>
      <td>-0.467506</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>77</th>
      <td>0</td>
      <td>associate's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-0.931773</td>
      <td>0.425397</td>
      <td>0.110554</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>78</th>
      <td>0</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>-0.289663</td>
      <td>0.648508</td>
      <td>0.905386</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>79</th>
      <td>0</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>-0.146972</td>
      <td>0.202287</td>
      <td>0.833128</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>80</th>
      <td>1</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>0.637829</td>
      <td>0.351027</td>
      <td>0.544099</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>81</th>
      <td>1</td>
      <td>bachelor's degree</td>
      <td>standard</td>
      <td>completed</td>
      <td>1.279939</td>
      <td>1.169099</td>
      <td>1.411188</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>82</th>
      <td>1</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>0.138410</td>
      <td>-0.467045</td>
      <td>-0.756535</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>83</th>
      <td>1</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-1.288501</td>
      <td>-0.690155</td>
      <td>-0.973308</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>84</th>
      <td>0</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.218317</td>
      <td>-0.318304</td>
      <td>0.399584</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>85</th>
      <td>1</td>
      <td>associate's degree</td>
      <td>standard</td>
      <td>none</td>
      <td>-0.503700</td>
      <td>-0.838896</td>
      <td>-0.178476</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>86</th>
      <td>0</td>
      <td>some college</td>
      <td>standard</td>
      <td>completed</td>
      <td>-0.361008</td>
      <td>0.574138</td>
      <td>0.544099</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>87</th>
      <td>1</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-0.075626</td>
      <td>-0.690155</td>
      <td>-0.178476</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>88</th>
      <td>0</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>0.923211</td>
      <td>1.094729</td>
      <td>1.122158</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>89</th>
      <td>0</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-0.575045</td>
      <td>-0.169564</td>
      <td>-0.033961</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>90</th>
      <td>1</td>
      <td>high school</td>
      <td>standard</td>
      <td>completed</td>
      <td>2.278777</td>
      <td>1.764061</td>
      <td>2.133762</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>91</th>
      <td>1</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>0.495138</td>
      <td>0.053547</td>
      <td>-0.033961</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>92</th>
      <td>0</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>0.423793</td>
      <td>0.722878</td>
      <td>0.688613</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>93</th>
      <td>0</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-1.502537</td>
      <td>-0.764526</td>
      <td>-0.322991</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>94</th>
      <td>0</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>0.281101</td>
      <td>1.615320</td>
      <td>1.194416</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>95</th>
      <td>0</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-0.432354</td>
      <td>0.648508</td>
      <td>0.977643</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>96</th>
      <td>0</td>
      <td>high school</td>
      <td>free/reduced</td>
      <td>none</td>
      <td>-0.361008</td>
      <td>-0.392675</td>
      <td>-0.395248</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>97</th>
      <td>0</td>
      <td>some college</td>
      <td>standard</td>
      <td>none</td>
      <td>0.281101</td>
      <td>1.094729</td>
      <td>1.194416</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>98</th>
      <td>1</td>
      <td>some high school</td>
      <td>standard</td>
      <td>none</td>
      <td>1.708013</td>
      <td>1.169099</td>
      <td>0.905386</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>99</th>
      <td>0</td>
      <td>master's degree</td>
      <td>free/reduced</td>
      <td>completed</td>
      <td>-0.004281</td>
      <td>1.540950</td>
      <td>1.555703</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
<p>100 rows × 12 columns</p>
</div>

In [76]:
# Changing multiple columns to one-hot representation
exam_data = pd.get_dummies(exam_data, columns=['parental level of education',
                                               'lunch',
                                               'test preparation course'])

KeyError: "['parental level of education' 'lunch' 'test preparation course'] not in index"

In [78]:
exam_data.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>gender</th>
      <th>math score</th>
      <th>reading score</th>
      <th>writing score</th>
      <th>race/ethnicity_group A</th>
      <th>race/ethnicity_group B</th>
      <th>race/ethnicity_group C</th>
      <th>race/ethnicity_group D</th>
      <th>race/ethnicity_group E</th>
      <th>parental level of education_associate's degree</th>
      <th>parental level of education_bachelor's degree</th>
      <th>parental level of education_high school</th>
      <th>parental level of education_master's degree</th>
      <th>parental level of education_some college</th>
      <th>parental level of education_some high school</th>
      <th>lunch_free/reduced</th>
      <th>lunch_standard</th>
      <th>test preparation course_completed</th>
      <th>test preparation course_none</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>0.994557</td>
      <td>0.574138</td>
      <td>1.049901</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>-0.646391</td>
      <td>-0.169564</td>
      <td>-0.178476</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1</td>
      <td>1.493976</td>
      <td>0.053547</td>
      <td>0.544099</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0</td>
      <td>0.209756</td>
      <td>0.797248</td>
      <td>0.688613</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>-1.145810</td>
      <td>0.053547</td>
      <td>-0.395248</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>